# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1122, 699)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height());
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 771, 501))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.content_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.content_label.setStatusTip(_fromUtf8(""))
        self.content_label.setFrameShape(QtGui.QFrame.Box)
        self.content_label.setFrameShadow(QtGui.QFrame.Raised)
        self.content_label.setText(_fromUtf8(""))
        self.content_label.setScaledContents(False)
        self.content_label.setAlignment(QtCore.Qt.AlignCenter)
        self.content_label.setObjectName(_fromUtf8("content_label"))
        self.horizontalLayout.addWidget(self.content_label)
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(810, 320, 131, 171))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.youhua = QtGui.QPushButton(self.formLayoutWidget_2)
        self.youhua.setObjectName(_fromUtf8("youhua"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.youhua)
        self.shanshui = QtGui.QPushButton(self.formLayoutWidget_2)
        self.shanshui.setObjectName(_fromUtf8("shanshui"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.shanshui)
        self.shuimohua = QtGui.QPushButton(self.formLayoutWidget_2)
        self.shuimohua.setObjectName(_fromUtf8("shuimohua"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.shuimohua)
        self.waveButton = QtGui.QPushButton(self.formLayoutWidget_2)
        self.waveButton.setObjectName(_fromUtf8("waveButton"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.waveButton)
        self.museButton = QtGui.QPushButton(self.formLayoutWidget_2)
        self.museButton.setObjectName(_fromUtf8("museButton"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.museButton)
        self.runButton = QtGui.QPushButton(self.centralWidget)
        self.runButton.setGeometry(QtCore.QRect(130, 590, 80, 25))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(910, 280, 91, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.resetButton = QtGui.QPushButton(self.centralWidget)
        self.resetButton.setGeometry(QtCore.QRect(240, 590, 80, 25))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(830, 50, 261, 201))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.style_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.style_label.sizePolicy().hasHeightForWidth())
        self.style_label.setSizePolicy(sizePolicy)
        self.style_label.setText(_fromUtf8(""))
        self.style_label.setScaledContents(True)
        self.style_label.setObjectName(_fromUtf8("style_label"))
        self.horizontalLayout_3.addWidget(self.style_label)
        self.contentButton = QtGui.QPushButton(self.centralWidget)
        self.contentButton.setGeometry(QtCore.QRect(360, 590, 119, 25))
        self.contentButton.setObjectName(_fromUtf8("contentButton"))
        self.localButton = QtGui.QPushButton(self.centralWidget)
        self.localButton.setGeometry(QtCore.QRect(510, 590, 119, 25))
        self.localButton.setObjectName(_fromUtf8("localButton"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(380, 20, 91, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(930, 20, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(980, 320, 111, 171))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.grilButton = QtGui.QPushButton(self.formLayoutWidget)
        self.grilButton.setObjectName(_fromUtf8("grilButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.grilButton)
        self.gril2Button = QtGui.QPushButton(self.formLayoutWidget)
        self.gril2Button.setObjectName(_fromUtf8("gril2Button"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.gril2Button)
        self.sailButton = QtGui.QPushButton(self.formLayoutWidget)
        self.sailButton.setObjectName(_fromUtf8("sailButton"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.sailButton)
        self.headButton = QtGui.QPushButton(self.formLayoutWidget)
        self.headButton.setObjectName(_fromUtf8("headButton"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.headButton)
        self.sumiaoButton = QtGui.QPushButton(self.formLayoutWidget)
        self.sumiaoButton.setObjectName(_fromUtf8("sumiaoButton"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.sumiaoButton)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_file = QtGui.QAction(MainWindow)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.mainToolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Neural Style Transfer", None))
        self.youhua.setText(_translate("MainWindow", "scream", None))
        self.shanshui.setText(_translate("MainWindow", "rain_princess", None))
        self.shuimohua.setText(_translate("MainWindow", "wreck", None))
        self.waveButton.setText(_translate("MainWindow", "wave", None))
        self.museButton.setText(_translate("MainWindow", "la_muse", None))
        self.runButton.setText(_translate("MainWindow", "RUN", None))
        self.label_4.setText(_translate("MainWindow", "Styles Choices", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.contentButton.setText(_translate("MainWindow", "Open Image", None))
        self.localButton.setText(_translate("MainWindow", "Local Style", None))
        self.label.setText(_translate("MainWindow", "Content Image", None))
        self.label_2.setText(_translate("MainWindow", "Style Image", None))
        self.grilButton.setText(_translate("MainWindow", "Gril", None))
        self.gril2Button.setText(_translate("MainWindow", "Gril2", None))
        self.sailButton.setText(_translate("MainWindow", "Sail", None))
        self.headButton.setText(_translate("MainWindow", "head", None))
        self.sumiaoButton.setText(_translate("MainWindow", "sumiao", None))
        self.actionOpen_file.setText(_translate("MainWindow", "open file", None))
        self.actionOpen_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save ", None))

